/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { Suspense, useRef, useState, useEffect } from 'react'
import { useGLTF, Text } from '@react-three/drei'
//imported functions

function DisplayPlane(props) {

  return (
    <mesh
      position={[-11.25, 23.5, 5]}
    >
      <planeBufferGeometry attach="geometry" args={[27.5, 27.5]} />
      <meshBasicMaterial attach="material" map={props.texture}/>
    </mesh>
  )

}

export default function Model(props) {
  const group = useRef()

  const screenRef = useRef()

  //index of texture to display from [textures]
  const [currentTexture, setCurrentTexture] = useState(0);

  const [texturesReady, setTexturesReady] = useState(false);

  useEffect(() => {
    props.mmUnwrap();
  }, [])

  useEffect(() => {
    if(props.DLtextures !== null) {
      setTexturesReady(true);
    }
  }, [props.DLtextures])

  useEffect(() => {
    const timeout = setTimeout(() => {
      if(currentTexture === props.DLtextures.length - 1 ) {
        setCurrentTexture(0);
      } else {
        setCurrentTexture(currentTexture + 1);
      }
    }, 30);
    return () => {
      clearTimeout(timeout);
    };
  }, [currentTexture]);

  const { nodes, materials } = useGLTF('/Optimized_Desk_Scene_Final.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Commodore" rotation={[Math.PI / 2, 0, -0.13]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            name="Case_for_Josh"
            geometry={nodes.Case_for_Josh.geometry}
            material={nodes.Case_for_Josh.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive01"
            geometry={nodes.Commodore_1541_Diskette_Drive01.geometry}
            material={nodes.Commodore_1541_Diskette_Drive01.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_01"
            geometry={nodes.Commodore_1541_Diskette_Drive_01.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_01.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_02"
            geometry={nodes.Commodore_1541_Diskette_Drive_02.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_02.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_03"
            geometry={nodes.Commodore_1541_Diskette_Drive_03.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_03.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_04"
            geometry={nodes.Commodore_1541_Diskette_Drive_04.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_04.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_05"
            geometry={nodes.Commodore_1541_Diskette_Drive_05.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_05.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_06"
            geometry={nodes.Commodore_1541_Diskette_Drive_06.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_06.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_07"
            geometry={nodes.Commodore_1541_Diskette_Drive_07.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_07.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_08"
            geometry={nodes.Commodore_1541_Diskette_Drive_08.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_08.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_09"
            geometry={nodes.Commodore_1541_Diskette_Drive_09.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_09.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_10"
            geometry={nodes.Commodore_1541_Diskette_Drive_10.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_10.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_11"
            geometry={nodes.Commodore_1541_Diskette_Drive_11.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_11.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_12"
            geometry={nodes.Commodore_1541_Diskette_Drive_12.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_12.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_13"
            geometry={nodes.Commodore_1541_Diskette_Drive_13.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_13.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_14"
            geometry={nodes.Commodore_1541_Diskette_Drive_14.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_14.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_15"
            geometry={nodes.Commodore_1541_Diskette_Drive_15.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_15.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_16"
            geometry={nodes.Commodore_1541_Diskette_Drive_16.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_16.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_17"
            geometry={nodes.Commodore_1541_Diskette_Drive_17.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_17.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_18"
            geometry={nodes.Commodore_1541_Diskette_Drive_18.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_18.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_19"
            geometry={nodes.Commodore_1541_Diskette_Drive_19.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_19.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_20"
            geometry={nodes.Commodore_1541_Diskette_Drive_20.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_20.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_21"
            geometry={nodes.Commodore_1541_Diskette_Drive_21.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_21.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_22"
            geometry={nodes.Commodore_1541_Diskette_Drive_22.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_22.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_23"
            geometry={nodes.Commodore_1541_Diskette_Drive_23.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_23.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_24"
            geometry={nodes.Commodore_1541_Diskette_Drive_24.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_24.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_26"
            geometry={nodes.Commodore_1541_Diskette_Drive_26.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_26.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_27"
            geometry={nodes.Commodore_1541_Diskette_Drive_27.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_27.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1541_Diskette_Drive_28"
            geometry={nodes.Commodore_1541_Diskette_Drive_28.geometry}
            material={nodes.Commodore_1541_Diskette_Drive_28.material}
            position={[-5.79, 15.55, 0]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor01"
            geometry={nodes.Commodore_1702_Monitor01.geometry}
            material={nodes.Commodore_1702_Monitor01.material}
            position={[0, 0, -2.56]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_01"
            geometry={nodes.Commodore_1702_Monitor_01.geometry}
            material={nodes.Commodore_1702_Monitor_01.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />

          <mesh
            name="Commodore_1702_Monitor_03"
            geometry={nodes.Commodore_1702_Monitor_03.geometry}
            material={nodes.Commodore_1702_Monitor_03.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_04"
            geometry={nodes.Commodore_1702_Monitor_04.geometry}
            material={nodes.Commodore_1702_Monitor_04.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_05"
            geometry={nodes.Commodore_1702_Monitor_05.geometry}
            material={nodes.Commodore_1702_Monitor_05.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_06"
            geometry={nodes.Commodore_1702_Monitor_06.geometry}
            material={nodes.Commodore_1702_Monitor_06.material}
            position={[0, 0, -2.65]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_07"
            geometry={nodes.Commodore_1702_Monitor_07.geometry}
            material={nodes.Commodore_1702_Monitor_07.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_08"
            geometry={nodes.Commodore_1702_Monitor_08.geometry}
            material={nodes.Commodore_1702_Monitor_08.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_09"
            geometry={nodes.Commodore_1702_Monitor_09.geometry}
            material={nodes.Commodore_1702_Monitor_09.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_10"
            geometry={nodes.Commodore_1702_Monitor_10.geometry}
            material={nodes.Commodore_1702_Monitor_10.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_11"
            geometry={nodes.Commodore_1702_Monitor_11.geometry}
            material={nodes.Commodore_1702_Monitor_11.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_12"
            geometry={nodes.Commodore_1702_Monitor_12.geometry}
            material={nodes.Commodore_1702_Monitor_12.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_13"
            geometry={nodes.Commodore_1702_Monitor_13.geometry}
            material={nodes.Commodore_1702_Monitor_13.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_14"
            geometry={nodes.Commodore_1702_Monitor_14.geometry}
            material={nodes.Commodore_1702_Monitor_14.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_15"
            geometry={nodes.Commodore_1702_Monitor_15.geometry}
            material={nodes.Commodore_1702_Monitor_15.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_16"
            geometry={nodes.Commodore_1702_Monitor_16.geometry}
            material={nodes.Commodore_1702_Monitor_16.material}
            position={[0, 0, -4.25]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_17"
            geometry={nodes.Commodore_1702_Monitor_17.geometry}
            material={nodes.Commodore_1702_Monitor_17.material}
            position={[0, 0, -4.25]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_18"
            geometry={nodes.Commodore_1702_Monitor_18.geometry}
            material={nodes.Commodore_1702_Monitor_18.material}
            position={[0, 0, -4.25]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_19"
            geometry={nodes.Commodore_1702_Monitor_19.geometry}
            material={nodes.Commodore_1702_Monitor_19.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_20"
            geometry={nodes.Commodore_1702_Monitor_20.geometry}
            material={nodes.Commodore_1702_Monitor_20.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_21"
            geometry={nodes.Commodore_1702_Monitor_21.geometry}
            material={nodes.Commodore_1702_Monitor_21.material}
            position={[0, 0, -4.3]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_22"
            geometry={nodes.Commodore_1702_Monitor_22.geometry}
            material={nodes.Commodore_1702_Monitor_22.material}
            position={[0, 0, -4.25]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_23"
            geometry={nodes.Commodore_1702_Monitor_23.geometry}
            material={nodes.Commodore_1702_Monitor_23.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_25"
            geometry={nodes.Commodore_1702_Monitor_25.geometry}
            material={nodes.Commodore_1702_Monitor_25.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_26"
            geometry={nodes.Commodore_1702_Monitor_26.geometry}
            material={nodes.Commodore_1702_Monitor_26.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_27"
            geometry={nodes.Commodore_1702_Monitor_27.geometry}
            material={nodes.Commodore_1702_Monitor_27.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_29"
            geometry={nodes.Commodore_1702_Monitor_29.geometry}
            material={nodes.Commodore_1702_Monitor_29.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_30"
            geometry={nodes.Commodore_1702_Monitor_30.geometry}
            material={nodes.Commodore_1702_Monitor_30.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_31"
            geometry={nodes.Commodore_1702_Monitor_31.geometry}
            material={nodes.Commodore_1702_Monitor_31.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_32"
            geometry={nodes.Commodore_1702_Monitor_32.geometry}
            material={nodes.Commodore_1702_Monitor_32.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_33"
            geometry={nodes.Commodore_1702_Monitor_33.geometry}
            material={nodes.Commodore_1702_Monitor_33.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_34"
            geometry={nodes.Commodore_1702_Monitor_34.geometry}
            material={nodes.Commodore_1702_Monitor_34.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_35"
            geometry={nodes.Commodore_1702_Monitor_35.geometry}
            material={nodes.Commodore_1702_Monitor_35.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_36"
            geometry={nodes.Commodore_1702_Monitor_36.geometry}
            material={nodes.Commodore_1702_Monitor_36.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_37"
            geometry={nodes.Commodore_1702_Monitor_37.geometry}
            material={nodes.Commodore_1702_Monitor_37.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_38"
            geometry={nodes.Commodore_1702_Monitor_38.geometry}
            material={nodes.Commodore_1702_Monitor_38.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_39"
            geometry={nodes.Commodore_1702_Monitor_39.geometry}
            material={nodes.Commodore_1702_Monitor_39.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_40"
            geometry={nodes.Commodore_1702_Monitor_40.geometry}
            material={nodes.Commodore_1702_Monitor_40.material}
            position={[0, 0, -4.27]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_41"
            geometry={nodes.Commodore_1702_Monitor_41.geometry}
            material={nodes.Commodore_1702_Monitor_41.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_42"
            geometry={nodes.Commodore_1702_Monitor_42.geometry}
            material={nodes.Commodore_1702_Monitor_42.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_43"
            geometry={nodes.Commodore_1702_Monitor_43.geometry}
            material={nodes.Commodore_1702_Monitor_43.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_44"
            geometry={nodes.Commodore_1702_Monitor_44.geometry}
            material={nodes.Commodore_1702_Monitor_44.material}
            position={[0, 0, -4.25]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_45"
            geometry={nodes.Commodore_1702_Monitor_45.geometry}
            material={nodes.Commodore_1702_Monitor_45.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_1702_Monitor_46"
            geometry={nodes.Commodore_1702_Monitor_46.geometry}
            material={nodes.Commodore_1702_Monitor_46.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_01"
            geometry={nodes.Commodore_64_Keyboard_01.geometry}
            material={nodes.Commodore_64_Keyboard_01.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_02"
            geometry={nodes.Commodore_64_Keyboard_02.geometry}
            material={nodes.Commodore_64_Keyboard_02.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_03"
            geometry={nodes.Commodore_64_Keyboard_03.geometry}
            material={nodes.Commodore_64_Keyboard_03.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_04"
            geometry={nodes.Commodore_64_Keyboard_04.geometry}
            material={nodes.Commodore_64_Keyboard_04.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_07"
            geometry={nodes.Commodore_64_Keyboard_07.geometry}
            material={nodes.Commodore_64_Keyboard_07.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_08"
            geometry={nodes.Commodore_64_Keyboard_08.geometry}
            material={nodes.Commodore_64_Keyboard_08.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_09"
            geometry={nodes.Commodore_64_Keyboard_09.geometry}
            material={nodes.Commodore_64_Keyboard_09.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_10"
            geometry={nodes.Commodore_64_Keyboard_10.geometry}
            material={nodes.Commodore_64_Keyboard_10.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_11"
            geometry={nodes.Commodore_64_Keyboard_11.geometry}
            material={nodes.Commodore_64_Keyboard_11.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_12"
            geometry={nodes.Commodore_64_Keyboard_12.geometry}
            material={nodes.Commodore_64_Keyboard_12.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_13"
            geometry={nodes.Commodore_64_Keyboard_13.geometry}
            material={nodes.Commodore_64_Keyboard_13.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_14"
            geometry={nodes.Commodore_64_Keyboard_14.geometry}
            material={nodes.Commodore_64_Keyboard_14.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_15"
            geometry={nodes.Commodore_64_Keyboard_15.geometry}
            material={nodes.Commodore_64_Keyboard_15.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_16"
            geometry={nodes.Commodore_64_Keyboard_16.geometry}
            material={nodes.Commodore_64_Keyboard_16.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_18"
            geometry={nodes.Commodore_64_Keyboard_18.geometry}
            material={nodes.Commodore_64_Keyboard_18.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_19"
            geometry={nodes.Commodore_64_Keyboard_19.geometry}
            material={nodes.Commodore_64_Keyboard_19.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_20"
            geometry={nodes.Commodore_64_Keyboard_20.geometry}
            material={nodes.Commodore_64_Keyboard_20.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_21"
            geometry={nodes.Commodore_64_Keyboard_21.geometry}
            material={nodes.Commodore_64_Keyboard_21.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_22"
            geometry={nodes.Commodore_64_Keyboard_22.geometry}
            material={nodes.Commodore_64_Keyboard_22.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_23"
            geometry={nodes.Commodore_64_Keyboard_23.geometry}
            material={nodes.Commodore_64_Keyboard_23.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_24"
            geometry={nodes.Commodore_64_Keyboard_24.geometry}
            material={nodes.Commodore_64_Keyboard_24.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_25"
            geometry={nodes.Commodore_64_Keyboard_25.geometry}
            material={nodes.Commodore_64_Keyboard_25.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_26"
            geometry={nodes.Commodore_64_Keyboard_26.geometry}
            material={nodes.Commodore_64_Keyboard_26.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_27"
            geometry={nodes.Commodore_64_Keyboard_27.geometry}
            material={nodes.Commodore_64_Keyboard_27.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_28"
            geometry={nodes.Commodore_64_Keyboard_28.geometry}
            material={nodes.Commodore_64_Keyboard_28.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_29"
            geometry={nodes.Commodore_64_Keyboard_29.geometry}
            material={nodes.Commodore_64_Keyboard_29.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_30"
            geometry={nodes.Commodore_64_Keyboard_30.geometry}
            material={nodes.Commodore_64_Keyboard_30.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_31"
            geometry={nodes.Commodore_64_Keyboard_31.geometry}
            material={materials.mat_green_dark}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_32"
            geometry={nodes.Commodore_64_Keyboard_32.geometry}
            material={nodes.Commodore_64_Keyboard_32.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_33"
            geometry={nodes.Commodore_64_Keyboard_33.geometry}
            material={nodes.Commodore_64_Keyboard_33.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_34"
            geometry={nodes.Commodore_64_Keyboard_34.geometry}
            material={nodes.Commodore_64_Keyboard_34.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_35"
            geometry={nodes.Commodore_64_Keyboard_35.geometry}
            material={nodes.Commodore_64_Keyboard_35.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_36"
            geometry={nodes.Commodore_64_Keyboard_36.geometry}
            material={nodes.Commodore_64_Keyboard_36.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_37"
            geometry={nodes.Commodore_64_Keyboard_37.geometry}
            material={nodes.Commodore_64_Keyboard_37.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_38"
            geometry={nodes.Commodore_64_Keyboard_38.geometry}
            material={nodes.Commodore_64_Keyboard_38.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_39"
            geometry={nodes.Commodore_64_Keyboard_39.geometry}
            material={nodes.Commodore_64_Keyboard_39.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_40"
            geometry={nodes.Commodore_64_Keyboard_40.geometry}
            material={nodes.Commodore_64_Keyboard_40.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_41"
            geometry={nodes.Commodore_64_Keyboard_41.geometry}
            material={nodes.Commodore_64_Keyboard_41.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_42"
            geometry={nodes.Commodore_64_Keyboard_42.geometry}
            material={nodes.Commodore_64_Keyboard_42.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
          <mesh
            name="Commodore_64_Keyboard_43"
            geometry={nodes.Commodore_64_Keyboard_43.geometry}
            material={nodes.Commodore_64_Keyboard_43.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />

          <group 
            name={"screen"}
            position={[0, 0, 0.12]}
            rotation={[-Math.PI / 2, -0.36, 0]}
          >
            <mesh
              ref={screenRef}
              name="Dreamloop_Goes_Here"
              geometry={nodes.Dreamloop_Goes_Here.geometry}
            >
              <meshBasicMaterial color="white" transparent={true} opacity={0.2}/>
              
            </mesh>


          { texturesReady ? <DisplayPlane texture={props.DLtextures[currentTexture]}/> : 
            <mesh
              position={[-11.25, 23.5, 5]}
            >
              <planeBufferGeometry attach="geometry" args={[27.5, 27.5]} />
              <meshBasicMaterial attach="material" color="hotpink"/>
            </mesh>
          }

          </group>
          
          <mesh
            name="KEYBOARD_for_start"
            geometry={nodes.KEYBOARD_for_start.geometry}
            material={nodes.KEYBOARD_for_start.material}
            rotation={[-Math.PI / 2, -0.36, 0]}
          />
        </group>
        <group name="Shelf" position={[0, 1.16, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <group name="wall_shelf_112" position={[0, 4.96, 0.42]}>
            <mesh
              name="112_"
              geometry={nodes['112_'].geometry}
              material={materials['Black Wood']}
              position={[-6.14, -37.46, 59.13]}
              rotation={[-1.56, 0, 0]}
              scale={[2.87, 2.87, 2.87]}
            />
          </group>
        </group>
        <group name="Gameboy" position={[0, 0.82, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <group
            name="gameboyMesh"
            position={[-43.38, 32.29, 80.85]}
            rotation={[-Math.PI / 2, 1.02, 0]}
            scale={[5.45, 5.45, 5.45]}>
            <mesh name="Mesh117" geometry={nodes.Mesh117.geometry} material={materials['gameboy:D_pad_002']} />
            <mesh
              name="Mesh117_1"
              geometry={nodes.Mesh117_1.geometry}
              material={materials['gameboy:Start_select_002']}
            />
            <mesh name="Mesh117_2" geometry={nodes.Mesh117_2.geometry} material={materials['gameboy:Material_003']} />
            <mesh name="Mesh117_3" geometry={nodes.Mesh117_3.geometry} material={materials['gameboy:Material_005']} />
            <mesh name="Mesh117_4" geometry={nodes.Mesh117_4.geometry} material={materials['gameboy:A___B_002']} />
          </group>
        </group>
        <group
          name="VHS_Cassettes"
          position={[-0.34, 0.58, -0.23]}
          rotation={[Math.PI / 2, 0, 0.22]}
          scale={[0.01, 0.01, 0.01]}>
          <group name="VHS_cassete1VHS_TAPE">
            <mesh
              name="VHS_cassete1pPlane10"
              geometry={nodes.VHS_cassete1pPlane10.geometry}
              material={nodes.VHS_cassete1pPlane10.material}
              position={[16.27, 0, 0]}
            />
            <mesh
              name="VHS_cassete1pPlane11"
              geometry={nodes.VHS_cassete1pPlane11.geometry}
              material={nodes.VHS_cassete1pPlane11.material}
              position={[16.27, 0, 0]}
            />
            <mesh
              name="VHS_cassete1pPlane2"
              geometry={nodes.VHS_cassete1pPlane2.geometry}
              material={nodes.VHS_cassete1pPlane2.material}
              position={[16.27, 0, 0]}
            />
            <mesh
              name="VHS_cassete1pPlane3"
              geometry={nodes.VHS_cassete1pPlane3.geometry}
              material={nodes.VHS_cassete1pPlane3.material}
              position={[16.27, 0, 0]}
            />
            <mesh
              name="VHS_cassete1pPlane4"
              geometry={nodes.VHS_cassete1pPlane4.geometry}
              material={nodes.VHS_cassete1pPlane4.material}
              position={[16.27, 0, 0]}
            />
            <mesh
              name="VHS_cassete1pPlane5"
              geometry={nodes.VHS_cassete1pPlane5.geometry}
              material={nodes.VHS_cassete1pPlane5.material}
              position={[16.27, 0, 0]}
            />
            <mesh
              name="VHS_cassete1pPlane6"
              geometry={nodes.VHS_cassete1pPlane6.geometry}
              material={nodes.VHS_cassete1pPlane6.material}
              position={[16.27, 0, 0]}
            />
            <mesh
              name="VHS_cassete1pPlane7"
              geometry={nodes.VHS_cassete1pPlane7.geometry}
              material={nodes.VHS_cassete1pPlane7.material}
              position={[16.27, 0, 0]}
            />
            <mesh
              name="VHS_cassete1pPlane8"
              geometry={nodes.VHS_cassete1pPlane8.geometry}
              material={nodes.VHS_cassete1pPlane8.material}
              position={[16.27, 0, 0]}
            />
            <mesh
              name="VHS_cassete1pPlane9"
              geometry={nodes.VHS_cassete1pPlane9.geometry}
              material={nodes.VHS_cassete1pPlane9.material}
              position={[16.27, 0, 0]}
            />
          </group>
        </group>
        <group name="Rubiks"
         position={[-0.29, 0.59, -0.19]}
         rotation={[Math.PI / 2, 0, -0.75]}
         scale={[1, 1, ]}>
          <group
            name="3x3_Scrambled"
            position={[61.17, 212.49, 172.6]}
            rotation={[0, 0.02, -Math.PI / 2]}
            scale={[1.99, 1.99, 1.99]}>
            <mesh name="Mesh128" geometry={nodes.Mesh128.geometry} material={materials.Black} />
            <mesh name="Mesh128_1" geometry={nodes.Mesh128_1.geometry} material={materials.White} />
            <mesh name="Mesh128_2" geometry={nodes.Mesh128_2.geometry} material={materials.Blue} />
            <mesh name="Mesh128_3" geometry={nodes.Mesh128_3.geometry} material={materials.Yellow} />
            <mesh name="Mesh128_4" geometry={nodes.Mesh128_4.geometry} material={materials.Red} />
            <mesh name="Mesh128_5" geometry={nodes.Mesh128_5.geometry} material={materials.Green} />
            <mesh name="Mesh128_6" geometry={nodes.Mesh128_6.geometry} material={materials.Orange} />
          </group>
        </group>
        <group name="group" rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            name="JFK_Desk1Cylinder001"
            geometry={nodes.JFK_Desk1Cylinder001.geometry}
            material={nodes.JFK_Desk1Cylinder001.material}
            position={[-32.97, 0, 91.42]}
            scale={[0.12, 0.12, 0.12]}
          />
          <mesh
            name="JFK_Desk1Line001"
            geometry={nodes.JFK_Desk1Line001.geometry}
            material={nodes.JFK_Desk1Line001.material}
            position={[-44.08, 39, 91.58]}
            rotation={[0, 0, -2.82]}
            scale={[0.12, 0.12, 0.12]}
          />
          <mesh
            name="JFK_Desk1Line065"
            geometry={nodes.JFK_Desk1Line065.geometry}
            material={materials['JFK_Desk1:wire_225143088']}
            position={[128.32, 139.03, 88.94]}
            rotation={[0, 0, -2.7]}
            scale={[0.12, 0.12, 0.12]}
          />
          <mesh
            name="JFK_Desk1Object001"
            geometry={nodes.JFK_Desk1Object001.geometry}
            material={nodes.JFK_Desk1Object001.material}
            position={[-32.97, 0, 88.94]}
            scale={[0.12, 0.12, 0.12]}
          />
          <mesh
            name="JFK_Desk1Rectangle001"
            geometry={nodes.JFK_Desk1Rectangle001.geometry}
            material={nodes.JFK_Desk1Rectangle001.material}
            position={[-32.97, 0, 91.42]}
            scale={[0.12, 0.12, 0.12]}
          />
        </group>
        <group
          name="Tape1"
          position={[-0.83, 0.22, -1.25]}
          rotation={[Math.PI, 0.17, -Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}>
          <mesh
            name="band_ribbon"
            geometry={nodes.band_ribbon.geometry}
            material={nodes.band_ribbon.material}
            position={[-21.31, 45.97, -114.64]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="band_ribbon001"
            geometry={nodes.band_ribbon001.geometry}
            material={nodes.band_ribbon001.material}
            position={[-21.31, 41.97, -114.64]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="band_ribbon002"
            geometry={nodes.band_ribbon002.geometry}
            material={nodes.band_ribbon002.material}
            position={[-21.31, 46.02, -116.09]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="band_ribbon003"
            geometry={nodes.band_ribbon003.geometry}
            material={nodes.band_ribbon003.material}
            position={[-21.31, 41.89, -116.2]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="Box001"
            geometry={nodes.Box001.geometry}
            material={materials.sponge3}
            position={[-21.31, 43.97, -117.47]}
            rotation={[Math.PI / 2, 0, Math.PI]}
            scale={[0.1, 0.1, 0.1]}
          />
          <mesh
            name="Box003"
            geometry={nodes.Box003.geometry}
            material={nodes.Box003.material}
            position={[-21.31, 43.97, -117.21]}
            rotation={[Math.PI / 2, 0, Math.PI]}
            scale={[0.1, 0.1, 0.1]}
          />
          <mesh
            name="Box004"
            geometry={nodes.Box004.geometry}
            material={nodes.Box004.material}
            position={[-21.31, 44.66, -117.54]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[0.1, 0.1, 0.1]}
          />
          <mesh
            name="Box005"
            geometry={nodes.Box005.geometry}
            material={nodes.Box005.material}
            position={[-21.31, 43.22, -117.54]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[0.1, 0.1, 0.1]}
          />
          <mesh
            name="Box006"
            geometry={nodes.Box006.geometry}
            material={materials.Metal4}
            position={[-21.31, 43.97, -117.46]}
            rotation={[Math.PI / 2, 0, Math.PI]}
            scale={[0.1, 0.1, 0.1]}
          />
          <mesh
            name="Circle001"
            geometry={nodes.Circle001.geometry}
            material={nodes.Circle001.material}
            position={[-21.09, 48.62, -112.09]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.1, 0.1, 0.1]}
          />
          <mesh
            name="Circle002"
            geometry={nodes.Circle002.geometry}
            material={nodes.Circle002.material}
            position={[-21.09, 39.31, -112.09]}
            rotation={[-1.31, 0, -Math.PI / 2]}
            scale={[0.1, 0.1, 0.1]}
          />
          <mesh
            name="Circle003"
            geometry={nodes.Circle003.geometry}
            material={nodes.Circle003.material}
            position={[-21.09, 39.31, -117.72]}
            rotation={[-2.53, 0, -Math.PI / 2]}
            scale={[0.1, 0.1, 0.1]}
          />
          <mesh
            name="Circle004"
            geometry={nodes.Circle004.geometry}
            material={nodes.Circle004.material}
            position={[-21, 43.97, -117.03]}
            rotation={[1.83, 0, -Math.PI / 2]}
            scale={[0.1, 0.1, 0.1]}
          />
          <mesh
            name="Circle005"
            geometry={nodes.Circle005.geometry}
            material={nodes.Circle005.material}
            position={[-21.09, 48.62, -117.72]}
            rotation={[-1.83, 0, -Math.PI / 2]}
            scale={[0.1, 0.1, 0.1]}
          />
          <mesh
            name="label"
            geometry={nodes.label.geometry}
            material={nodes.label.material}
            position={[-21.06, 43.97, -114.34]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="label001"
            geometry={nodes.label001.geometry}
            material={nodes.label001.material}
            position={[-21.56, 43.97, -114.34]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body"
            geometry={nodes.plastic_body.geometry}
            material={nodes.plastic_body.material}
            position={[-21.26, 48.96, -116.48]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body001"
            geometry={nodes.plastic_body001.geometry}
            material={nodes.plastic_body001.material}
            position={[-21.26, 38.98, -116.48]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body002"
            geometry={nodes.plastic_body002.geometry}
            material={nodes.plastic_body002.material}
            position={[-21.14, 43.97, -114.9]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body003"
            geometry={nodes.plastic_body003.geometry}
            material={nodes.plastic_body003.material}
            position={[-21.31, 47.82, -117.52]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body004"
            geometry={nodes.plastic_body004.geometry}
            material={nodes.plastic_body004.material}
            position={[-21.36, 48.96, -116.48]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body005"
            geometry={nodes.plastic_body005.geometry}
            material={nodes.plastic_body005.material}
            position={[-21.36, 38.98, -116.48]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body006"
            geometry={nodes.plastic_body006.geometry}
            material={nodes.plastic_body006.material}
            position={[-21.49, 43.97, -114.9]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body007"
            geometry={nodes.plastic_body007.geometry}
            material={nodes.plastic_body007.material}
            position={[-21.19, 43.06, -117.97]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body008"
            geometry={nodes.plastic_body008.geometry}
            material={nodes.plastic_body008.material}
            position={[-21.19, 44.87, -117.97]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body009"
            geometry={nodes.plastic_body009.geometry}
            material={nodes.plastic_body009.material}
            position={[-21.19, 42.17, -117.97]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body010"
            geometry={nodes.plastic_body010.geometry}
            material={nodes.plastic_body010.material}
            position={[-21.19, 45.77, -117.97]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body011"
            geometry={nodes.plastic_body011.geometry}
            material={nodes.plastic_body011.material}
            position={[-21.31, 46.82, -117.69]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body012"
            geometry={nodes.plastic_body012.geometry}
            material={nodes.plastic_body012.material}
            position={[-21.44, 44.87, -117.97]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body013"
            geometry={nodes.plastic_body013.geometry}
            material={nodes.plastic_body013.material}
            position={[-21.44, 45.77, -117.97]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body014"
            geometry={nodes.plastic_body014.geometry}
            material={nodes.plastic_body014.material}
            position={[-21.31, 41.97, -114.64]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body015"
            geometry={nodes.plastic_body015.geometry}
            material={nodes.plastic_body015.material}
            position={[-21.31, 45.97, -114.64]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body016"
            geometry={nodes.plastic_body016.geometry}
            material={nodes.plastic_body016.material}
            position={[-21.31, 41.12, -117.69]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body017"
            geometry={nodes.plastic_body017.geometry}
            material={nodes.plastic_body017.material}
            position={[-21.31, 40.11, -117.52]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_body018"
            geometry={nodes.plastic_body018.geometry}
            material={nodes.plastic_body018.material}
            position={[-21.44, 43.06, -117.97]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_bodys"
            geometry={nodes.plastic_bodys.geometry}
            material={nodes.plastic_bodys.material}
            position={[-21.44, 42.17, -117.97]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_white"
            geometry={nodes.plastic_white.geometry}
            material={nodes.plastic_white.material}
            position={[-21.31, 41.97, -114.64]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_white001"
            geometry={nodes.plastic_white001.geometry}
            material={nodes.plastic_white001.material}
            position={[-21.31, 47.82, -117.52]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_white002"
            geometry={nodes.plastic_white002.geometry}
            material={nodes.plastic_white002.material}
            position={[-21.31, 40.11, -117.52]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="plastic_white003"
            geometry={nodes.plastic_white003.geometry}
            material={nodes.plastic_white003.material}
            position={[-21.31, 45.97, -114.64]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="Text002"
            geometry={nodes.Text002.geometry}
            material={nodes.Text002.material}
            position={[-21.56, 46.39, -116.01]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.1, 0.1, 0.1]}
          />
          <mesh
            name="Text003"
            geometry={nodes.Text003.geometry}
            material={nodes.Text003.material}
            position={[-21.56, 44.19, -113.04]}
            rotation={[-0.09, 0, Math.PI / 2]}
            scale={[0.1, 0.1, 0.1]}
          />
          <mesh
            name="Text004"
            geometry={nodes.Text004.geometry}
            material={nodes.Text004.material}
            position={[-21.06, 46.82, -115.75]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.1, 0.1, 0.1]}
          />
          <mesh
            name="Text005"
            geometry={nodes.Text005.geometry}
            material={nodes.Text005.material}
            position={[-21.06, 41.4, -116.01]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.1, 0.1, 0.1]}
          />
          <mesh
            name="Text006"
            geometry={nodes.Text006.geometry}
            material={nodes.Text006.material}
            position={[-21.06, 44.19, -113.04]}
            rotation={[0.09, 0, -Math.PI / 2]}
            scale={[0.1, 0.1, 0.1]}
          />
          <mesh
            name="transparent__Screen"
            geometry={nodes.transparent__Screen.geometry}
            material={nodes.transparent__Screen.material}
            position={[-21.09, 43.97, -114.63]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
          <mesh
            name="transparent__Screen001"
            geometry={nodes.transparent__Screen001.geometry}
            material={nodes.transparent__Screen001.material}
            position={[-21.54, 43.97, -114.63]}
            rotation={[-Math.PI / 2, -1.57, 0]}
          />
        </group>
        <group name="Tape2" position={[-0.2, 0.015, -0.11]} rotation={[2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <group name="pasted__group1" position={[-68.34, -112.61, -24.9]} rotation={[Math.PI / 2, 0.17, -Math.PI / 2]}>
            <mesh
              name="pasted__band_ribbon"
              geometry={nodes.pasted__band_ribbon.geometry}
              material={nodes.pasted__band_ribbon.material}
              position={[-21.31, 45.97, -114.64]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__band_ribbon001"
              geometry={nodes.pasted__band_ribbon001.geometry}
              material={nodes.pasted__band_ribbon001.material}
              position={[-21.31, 41.97, -114.64]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__band_ribbon002"
              geometry={nodes.pasted__band_ribbon002.geometry}
              material={nodes.pasted__band_ribbon002.material}
              position={[-21.31, 46.02, -116.09]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__band_ribbon003"
              geometry={nodes.pasted__band_ribbon003.geometry}
              material={nodes.pasted__band_ribbon003.material}
              position={[-21.31, 41.89, -116.2]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__Box001"
              geometry={nodes.pasted__Box001.geometry}
              material={materials.pasted__sponge3}
              position={[-21.31, 43.97, -117.47]}
              rotation={[Math.PI / 2, 0, Math.PI]}
              scale={[0.1, 0.1, 0.1]}
            />
            <mesh
              name="pasted__Box003"
              geometry={nodes.pasted__Box003.geometry}
              material={nodes.pasted__Box003.material}
              position={[-21.31, 43.97, -117.21]}
              rotation={[Math.PI / 2, 0, Math.PI]}
              scale={[0.1, 0.1, 0.1]}
            />
            <mesh
              name="pasted__Box004"
              geometry={nodes.pasted__Box004.geometry}
              material={nodes.pasted__Box004.material}
              position={[-21.31, 44.66, -117.54]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[0.1, 0.1, 0.1]}
            />
            <mesh
              name="pasted__Box005"
              geometry={nodes.pasted__Box005.geometry}
              material={nodes.pasted__Box005.material}
              position={[-21.31, 43.22, -117.54]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[0.1, 0.1, 0.1]}
            />
            <mesh
              name="pasted__Box006"
              geometry={nodes.pasted__Box006.geometry}
              material={materials.pasted__Metal4}
              position={[-21.31, 43.97, -117.46]}
              rotation={[Math.PI / 2, 0, Math.PI]}
              scale={[0.1, 0.1, 0.1]}
            />
            <mesh
              name="pasted__Circle001"
              geometry={nodes.pasted__Circle001.geometry}
              material={nodes.pasted__Circle001.material}
              position={[-21.09, 48.62, -112.09]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.1, 0.1, 0.1]}
            />
            <mesh
              name="pasted__Circle002"
              geometry={nodes.pasted__Circle002.geometry}
              material={nodes.pasted__Circle002.material}
              position={[-21.09, 39.31, -112.09]}
              rotation={[-1.31, 0, -Math.PI / 2]}
              scale={[0.1, 0.1, 0.1]}
            />
            <mesh
              name="pasted__Circle003"
              geometry={nodes.pasted__Circle003.geometry}
              material={nodes.pasted__Circle003.material}
              position={[-21.09, 39.31, -117.72]}
              rotation={[-2.53, 0, -Math.PI / 2]}
              scale={[0.1, 0.1, 0.1]}
            />
            <mesh
              name="pasted__Circle004"
              geometry={nodes.pasted__Circle004.geometry}
              material={nodes.pasted__Circle004.material}
              position={[-21, 43.97, -117.03]}
              rotation={[1.83, 0, -Math.PI / 2]}
              scale={[0.1, 0.1, 0.1]}
            />
            <mesh
              name="pasted__Circle005"
              geometry={nodes.pasted__Circle005.geometry}
              material={nodes.pasted__Circle005.material}
              position={[-21.09, 48.62, -117.72]}
              rotation={[-1.83, 0, -Math.PI / 2]}
              scale={[0.1, 0.1, 0.1]}
            />
            <mesh
              name="pasted__label"
              geometry={nodes.pasted__label.geometry}
              material={nodes.pasted__label.material}
              position={[-21.06, 43.97, -114.34]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__label001"
              geometry={nodes.pasted__label001.geometry}
              material={nodes.pasted__label001.material}
              position={[-21.56, 43.97, -114.34]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body"
              geometry={nodes.pasted__plastic_body.geometry}
              material={nodes.pasted__plastic_body.material}
              position={[-21.26, 48.96, -116.48]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body001"
              geometry={nodes.pasted__plastic_body001.geometry}
              material={nodes.pasted__plastic_body001.material}
              position={[-21.26, 38.98, -116.48]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body002"
              geometry={nodes.pasted__plastic_body002.geometry}
              material={nodes.pasted__plastic_body002.material}
              position={[-21.14, 43.97, -114.9]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body003"
              geometry={nodes.pasted__plastic_body003.geometry}
              material={nodes.pasted__plastic_body003.material}
              position={[-21.31, 47.82, -117.52]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body004"
              geometry={nodes.pasted__plastic_body004.geometry}
              material={nodes.pasted__plastic_body004.material}
              position={[-21.36, 48.96, -116.48]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body005"
              geometry={nodes.pasted__plastic_body005.geometry}
              material={nodes.pasted__plastic_body005.material}
              position={[-21.36, 38.98, -116.48]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body006"
              geometry={nodes.pasted__plastic_body006.geometry}
              material={nodes.pasted__plastic_body006.material}
              position={[-21.49, 43.97, -114.9]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body007"
              geometry={nodes.pasted__plastic_body007.geometry}
              material={nodes.pasted__plastic_body007.material}
              position={[-21.19, 43.06, -117.97]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body008"
              geometry={nodes.pasted__plastic_body008.geometry}
              material={nodes.pasted__plastic_body008.material}
              position={[-21.19, 44.87, -117.97]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body009"
              geometry={nodes.pasted__plastic_body009.geometry}
              material={nodes.pasted__plastic_body009.material}
              position={[-21.19, 42.17, -117.97]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body010"
              geometry={nodes.pasted__plastic_body010.geometry}
              material={nodes.pasted__plastic_body010.material}
              position={[-21.19, 45.77, -117.97]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body011"
              geometry={nodes.pasted__plastic_body011.geometry}
              material={nodes.pasted__plastic_body011.material}
              position={[-21.31, 46.82, -117.69]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body012"
              geometry={nodes.pasted__plastic_body012.geometry}
              material={nodes.pasted__plastic_body012.material}
              position={[-21.44, 44.87, -117.97]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body013"
              geometry={nodes.pasted__plastic_body013.geometry}
              material={nodes.pasted__plastic_body013.material}
              position={[-21.44, 45.77, -117.97]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body014"
              geometry={nodes.pasted__plastic_body014.geometry}
              material={nodes.pasted__plastic_body014.material}
              position={[-21.31, 41.97, -114.64]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body015"
              geometry={nodes.pasted__plastic_body015.geometry}
              material={nodes.pasted__plastic_body015.material}
              position={[-21.31, 45.97, -114.64]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body016"
              geometry={nodes.pasted__plastic_body016.geometry}
              material={nodes.pasted__plastic_body016.material}
              position={[-21.31, 41.12, -117.69]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body017"
              geometry={nodes.pasted__plastic_body017.geometry}
              material={nodes.pasted__plastic_body017.material}
              position={[-21.31, 40.11, -117.52]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_body018"
              geometry={nodes.pasted__plastic_body018.geometry}
              material={nodes.pasted__plastic_body018.material}
              position={[-21.44, 43.06, -117.97]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_bodys"
              geometry={nodes.pasted__plastic_bodys.geometry}
              material={nodes.pasted__plastic_bodys.material}
              position={[-21.44, 42.17, -117.97]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_white"
              geometry={nodes.pasted__plastic_white.geometry}
              material={nodes.pasted__plastic_white.material}
              position={[-21.31, 41.97, -114.64]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_white001"
              geometry={nodes.pasted__plastic_white001.geometry}
              material={nodes.pasted__plastic_white001.material}
              position={[-21.31, 47.82, -117.52]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_white002"
              geometry={nodes.pasted__plastic_white002.geometry}
              material={nodes.pasted__plastic_white002.material}
              position={[-21.31, 40.11, -117.52]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__plastic_white003"
              geometry={nodes.pasted__plastic_white003.geometry}
              material={nodes.pasted__plastic_white003.material}
              position={[-21.31, 45.97, -114.64]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__Text002"
              geometry={nodes.pasted__Text002.geometry}
              material={nodes.pasted__Text002.material}
              position={[-21.56, 46.39, -116.01]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.1, 0.1, 0.1]}
            />
            <mesh
              name="pasted__Text003"
              geometry={nodes.pasted__Text003.geometry}
              material={nodes.pasted__Text003.material}
              position={[-21.56, 44.19, -113.04]}
              rotation={[-0.09, 0, Math.PI / 2]}
              scale={[0.1, 0.1, 0.1]}
            />
            <mesh
              name="pasted__Text004"
              geometry={nodes.pasted__Text004.geometry}
              material={nodes.pasted__Text004.material}
              position={[-21.06, 46.82, -115.75]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.1, 0.1, 0.1]}
            />
            <mesh
              name="pasted__Text005"
              geometry={nodes.pasted__Text005.geometry}
              material={nodes.pasted__Text005.material}
              position={[-21.06, 41.4, -116.01]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.1, 0.1, 0.1]}
            />
            <mesh
              name="pasted__transparent__Screen"
              geometry={nodes.pasted__transparent__Screen.geometry}
              material={nodes.pasted__transparent__Screen.material}
              position={[-21.09, 43.97, -114.63]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
            <mesh
              name="pasted__transparent__Screen001"
              geometry={nodes.pasted__transparent__Screen001.geometry}
              material={nodes.pasted__transparent__Screen001.material}
              position={[-21.54, 43.97, -114.63]}
              rotation={[-Math.PI / 2, -1.57, 0]}
            />
          </group>
        </group>
        <group name="Bust" position={[-0.68, 0.58, -0.18]} rotation={[Math.PI / 2, 0, 0.57]} scale={[0.08, 0.08, 0.08]}>
          <mesh
            name="ROMANBUST4"
            geometry={nodes.ROMANBUST4.geometry}
            material={materials.ROMAN_BUST_5}
            position={[-2.04, 1.26, -0.05]}
            rotation={[0, 0, -0.05]}
            scale={[0.87, 0.87, 0.87]}
          />
        </group>
        <group name="Lucky_Cat1" position={[-0.47, 0.03, -0.09]} rotation={[Math.PI / 2, 0, 1.51]} scale={[0, 0, 0]}>
          <mesh
            name="maneki_nekoCat_eyes"
            geometry={nodes.maneki_nekoCat_eyes.geometry}
            material={materials['maneki_neko:gatto_eyes4']}
            position={[0, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          />
          <mesh
            name="maneki_nekoCat_paw"
            geometry={nodes.maneki_nekoCat_paw.geometry}
            material={materials['maneki_neko:gatto_paw_black4.003']}
            position={[0, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          />
          <mesh
            name="maneki_nekoCat_torso"
            geometry={nodes.maneki_nekoCat_torso.geometry}
            material={materials['maneki_neko:gatto_torso_black4']}
            position={[0, 0, 41.2]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          />
        </group>
        <group name="Palm_Treee" rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.008, 0.008]}>
          <group
            name="maneki_nekoPalm_40"
            position={[34.61, -21.73, -0.56]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.01, 0.01, 0.01]}>
            <mesh
              name="Mesh232"
              geometry={nodes.Mesh232.geometry}
              material={materials['maneki_neko:Converted_LeavesTropical00_M11']}
            />
            <mesh
              name="Mesh232_1"
              geometry={nodes.Mesh232_1.geometry}
              material={materials['maneki_neko:LeavesTropical00_M151']}
            />
            <mesh
              name="Mesh232_2"
              geometry={nodes.Mesh232_2.geometry}
              material={materials['maneki_neko:LeavesTropical02_M1']}
            />
            <mesh
              name="Mesh232_3"
              geometry={nodes.Mesh232_3.geometry}
              material={materials['maneki_neko:Converted_LeavesTropical07_M18']}
            />
            <mesh
              name="Mesh232_4"
              geometry={nodes.Mesh232_4.geometry}
              material={materials['maneki_neko:Converted_LeavesTropical07_M15']}
            />
            <mesh
              name="Mesh232_5"
              geometry={nodes.Mesh232_5.geometry}
              material={materials['maneki_neko:LeavesTropical02_M1.1']}
            />
            <mesh
              name="Mesh232_6"
              geometry={nodes.Mesh232_6.geometry}
              material={materials['maneki_neko:Converted_bark palm 007']}
            />
            <mesh
              name="Mesh232_7"
              geometry={nodes.Mesh232_7.geometry}
              material={materials['maneki_neko:Converted_stone-grey.2']}
            />
            <mesh
              name="Mesh232_8"
              geometry={nodes.Mesh232_8.geometry}
              material={materials['maneki_neko:Converted_stone-Beige.2']}
            />
            <mesh
              name="Mesh232_9"
              geometry={nodes.Mesh232_9.geometry}
              material={materials['maneki_neko:Converted_flowers_ground.2']}
            />
            <mesh
              name="Mesh232_10"
              geometry={nodes.Mesh232_10.geometry}
              material={materials['maneki_neko:Converted_PlasterBare0206.2']}
            />
          </group>
        </group>
        <mesh
          name="Background"
          geometry={nodes.Background.geometry}
          material={nodes.Background.material}
          position={[0.13, 0.26, -0.47]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[100, 0.01, 100]}
        />

        <mesh
          name="Background"
          geometry={nodes.Background.geometry}
          material={nodes.Background.material}
          position={[0.13, -0.915, -0.47]}
          rotation={[Math.PI / 1, 0, 0]}
          scale={[100, 0.01, 100]}
        />


        <mesh
          name="Pyramid"
          geometry={nodes.Pyramid.geometry}
          material={nodes.Pyramid.material}
          position={[-0.57, 0.64, -0.26]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.16, 0.16, 0.16]}
        />
        <mesh
          name="boombox_dinamic_grid001"
          geometry={nodes.boombox_dinamic_grid001.geometry}
          material={materials['boombox_dinamic_grid.001']}
          position={[-0.74, 0.14, -0.27]}
          scale={[0.12, 0.12, 0.12]}
        />
        <mesh
          name="boombox_mesh001"
          geometry={nodes.boombox_mesh001.geometry}
          material={materials['boombox_material.001']}
          position={[-0.74, 0.14, -0.27]}
          scale={[0.12, 0.12, 0.12]}
        />
        <mesh
          name="decals_mesh001"
          geometry={nodes.decals_mesh001.geometry}
          material={materials['decals_mat.001']}
          position={[-0.74, 0, -0.27]}
          scale={[0.12, 0.12, 0.12]}
        />
        <mesh
          name="glass_mesh001"
          geometry={nodes.glass_mesh001.geometry}
          material={materials['glass_mat.001']}
          position={[-0.74, 0.14, -0.27]}
          scale={[0.12, 0.12, 0.12]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Optimized_Desk_Scene_Final.glb')
